/**
 * Renders docs/GENRES.md from the built-in genre profiles and the tag catalog, so the reference
 * never drifts from the code (`npm run docs:genres` writes it; a test fails when it is stale).
 */
import type { GenreProfile } from '../ir/types';
import { BUILTIN_GENRES, getGenre } from './genres';
import { getInstrument } from './instruments';
import { ALL_DRUM_STYLES, DRUM_STYLE_INFO } from './styles';
import { TAG_KINDS, listTags, tagGroups, type TagKind } from './tags';

const KIND_TITLE: Record<TagKind, string> = {
  style: 'Style tags (microgenres)',
  mood: 'Mood tags',
  era: 'Era tags',
  production: 'Production tags',
  vocal: 'Vocal tags',
  region: 'Region tags',
  rhythm: 'Rhythm and meter tags',
};

const pct = (w: number, total: number) => `${Math.round((w / (total || 1)) * 100)}%`;

function genreBlock(g: GenreProfile): string[] {
  const modeTotal = g.modes.reduce((t, m) => t + m.weight, 0);
  const meterTotal = g.meters.reduce((t, m) => t + m.weight, 0);
  const progs = [...g.harmony.progressions].sort((a, b) => b.weight - a.weight).slice(0, 3).map((p) => `\`${p.roman.join(' ')}\``);
  const core = g.instruments.filter((i) => i.essential).map((i) => getInstrument(i.instrumentId).name);
  const colour = g.instruments.filter((i) => !i.essential && i.weight >= 0.5).map((i) => getInstrument(i.instrumentId).name);
  const groove = [`\`${g.rhythm.drumStyle}\` drums`];
  if (g.rhythm.bassStyle) groove.push(`\`${g.rhythm.bassStyle}\` bass`);
  if (g.rhythm.compStyle) groove.push(`\`${g.rhythm.compStyle}\` comping`);
  if (g.rhythm.swing > 0.05) groove.push(`swing ${Math.round(g.rhythm.swing * 100)}%`);
  groove.push(`${g.rhythm.subdivision === 12 ? 'triplet' : `${g.rhythm.subdivision}th`} grid`);
  return [
    `### ${g.name} (\`${g.id}\`)`,
    '',
    g.description ?? '',
    '',
    `- **Tempo:** ${g.tempo.min}–${g.tempo.max} BPM (typically ${g.tempo.typical}) · **Meter:** ${g.meters.map((m) => `${m.numerator}/${m.denominator} ${pct(m.weight, meterTotal)}`).join(', ')}`,
    `- **Modes:** ${g.modes.map((m) => `${m.mode} ${pct(m.weight, modeTotal)}`).join(', ')}`,
    `- **Harmony:** ${progs.join(', ')} · extensions ${Math.round(g.harmony.extensionRate * 100)}% · ${g.harmony.harmonicRhythm} chord(s)/bar${g.harmony.powerChords ? ' · power chords' : ''}`,
    `- **Groove:** ${groove.join(', ')}`,
    `- **Forms:** ${g.structure.templates.map((t) => t.name).join('; ')}`,
    `- **Band:** ${core.join(', ')}${colour.length ? ` (often with ${colour.join(', ')})` : ''}`,
    `- **Sound:** ${g.production.description}`,
    '',
  ];
}

/** The full Markdown reference. */
export function renderGenresDoc(): string {
  const lines: string[] = [
    '# Genres and tags',
    '',
    '<!-- Generated by `npm run docs:genres` from packages/core/src/composer (genres.ts, styles.ts, tag-catalog.ts). Do not edit by hand. -->',
    '',
    `Song Deck ships **${BUILTIN_GENRES.length} genre profiles** — full rule sets for tempo, meter, modes, harmony, form, ` +
      `instrumentation, groove, dynamics and production that can be blended ("50% pop-punk / 30% emo / 20% cinematic") — and ` +
      `**${listTags().length} tags** that nudge a blend without being a full profile: ` +
      TAG_KINDS.map((k) => `${listTags(k).length} ${k}`).join(', ') +
      '.',
    '',
    'A style tag names parent genres: picked on its own it pulls the blend toward them ("midwest emo" → emo + indie rock); ' +
      'added to a blend it reshapes the profile (tempo window, groove, harmony, line-up, production). Mood, era, production, vocal, ' +
      'region and rhythm tags only reshape. Tag macro changes are applied at generation time on top of the song\'s own macros.',
    '',
    '## Genres',
    '',
  ];
  for (const g of BUILTIN_GENRES) lines.push(...genreBlock(g));
  lines.push('## Groove families (drum styles)', '', '| Drum style | Closest original family | Kit | Harmonic flavour | Hand percussion |', '| --- | --- | --- | --- | --- |');
  for (const d of ALL_DRUM_STYLES) {
    const i = DRUM_STYLE_INFO[d];
    lines.push(`| \`${d}\` | ${i.base} | ${i.electronic ? 'drum machine' : 'acoustic'} | ${i.flavor} | ${i.percussion} |`);
  }
  lines.push('');
  for (const kind of TAG_KINDS) {
    lines.push(`## ${KIND_TITLE[kind]}`, '');
    for (const { group, tags } of tagGroups(kind)) {
      lines.push(`### ${group}`, '');
      for (const t of tags) {
        const parents = t.parents?.length ? ` → ${t.parents.map((p) => getGenre(p.genreId)?.name ?? p.genreId).join(', ')}` : '';
        const aliases = t.aliases?.length ? ` _Also: ${t.aliases.join(', ')}._` : '';
        lines.push(`- **${t.name}** (\`${t.id}\`${parents}) — ${t.description ?? ''}${aliases}`);
      }
      lines.push('');
    }
  }
  return `${lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
}
