/**
 * Local model catalog for the Model Manager (spec §31, §61, §62): name, provider, version, size,
 * license, hardware requirements, capabilities. Sizes/requirements are approximate guidance for
 * compatibility classification, not hard limits.
 */
import { type Capability, LLM_BASE_CAPABILITIES } from './capabilities';
import type { LocalModelCategory, LocalModelEntry } from './hardware';

const LLM_LOCAL: Capability[] = [...LLM_BASE_CAPABILITIES, 'STRUCTURED_JSON'];

export const LOCAL_MODEL_CATALOG: LocalModelEntry[] = [
  {
    id: 'ace-step-1.5',
    name: 'ACE-Step 1.5',
    category: 'audio',
    runtime: 'ace-step-bridge',
    presetId: 'ace-step-local',
    version: '1.5',
    sizeGb: 8,
    license: 'Apache-2.0',
    requirements: { minVramGb: 4, recommendedVramGb: 8, minRamGb: 16, cpuOk: false },
    capabilities: ['TEXT_TO_MUSIC', 'AUDIO_TO_AUDIO', 'LYRIC_CONDITIONING', 'VOCAL_GENERATION', 'INSTRUMENTAL_ONLY', 'SECTION_GENERATION', 'REFERENCE_AUDIO', 'INPAINTING', 'OUTPAINTING', 'REGION_GENERATION'],
    homepage: 'https://github.com/ace-step/ACE-Step',
    notes: 'Local music generation with lyrics and audio conditioning; v1.5 advertises operation on under 4 GB VRAM.',
  },
  {
    id: 'diffsinger-openvpi',
    name: 'DiffSinger (OpenVPI)',
    category: 'vocals',
    runtime: 'diffsinger-bridge',
    presetId: 'diffsinger-local',
    version: '2.x',
    sizeGb: 1.5,
    license: 'Apache-2.0 (code); voicebanks carry their own licenses',
    requirements: { minVramGb: 0, recommendedVramGb: 4, minRamGb: 8, cpuOk: true, minCpuCores: 4 },
    capabilities: ['SINGING_SYNTHESIS', 'MIDI_CONDITIONING', 'LYRIC_CONDITIONING', 'REGION_GENERATION'],
    homepage: 'https://github.com/openvpi/DiffSinger',
    notes: 'Lyrics + MIDI singing synthesis with pitch, energy and breathiness controls (spec §34).',
  },
  {
    id: 'demucs-htdemucs',
    name: 'Demucs v4 (htdemucs)',
    category: 'separation',
    runtime: 'demucs-bridge',
    presetId: 'demucs-local',
    version: '4.0',
    sizeGb: 0.08,
    license: 'MIT',
    requirements: { minVramGb: 0, recommendedVramGb: 4, minRamGb: 8, cpuOk: true, minCpuCores: 4 },
    capabilities: ['SOURCE_SEPARATION', 'VOCAL_ISOLATION', 'STEM_OUTPUT'],
    homepage: 'https://github.com/adefossez/demucs',
    install: 'pip install demucs',
    notes: 'Hybrid Transformer Demucs: drums / bass / vocals / other.',
  },
  {
    id: 'demucs-htdemucs-ft',
    name: 'Demucs v4 fine-tuned (htdemucs_ft)',
    category: 'separation',
    runtime: 'demucs-bridge',
    presetId: 'demucs-local',
    version: '4.0',
    sizeGb: 0.32,
    license: 'MIT',
    requirements: { minVramGb: 0, recommendedVramGb: 6, minRamGb: 8, cpuOk: true, minCpuCores: 8 },
    capabilities: ['SOURCE_SEPARATION', 'VOCAL_ISOLATION', 'STEM_OUTPUT'],
    homepage: 'https://github.com/adefossez/demucs',
    install: 'pip install demucs',
    notes: 'Bag of 4 fine-tuned models: better quality, about 4× slower.',
  },
  {
    id: 'basic-pitch',
    name: 'Basic Pitch',
    category: 'transcription',
    runtime: 'basic-pitch-bridge',
    presetId: 'basic-pitch-local',
    version: '0.4',
    sizeGb: 0.02,
    license: 'Apache-2.0',
    requirements: { minVramGb: 0, recommendedVramGb: 0, minRamGb: 4, cpuOk: true, minCpuCores: 2 },
    capabilities: ['AUDIO_TRANSCRIPTION', 'AUDIO_TO_MIDI', 'PITCH_TRACKING'],
    homepage: 'https://github.com/spotify/basic-pitch',
    install: 'pip install basic-pitch',
    notes: 'Lightweight polyphonic audio-to-MIDI; runs well on CPU.',
  },
  {
    id: 'rvc-v2',
    name: 'RVC v2 (Retrieval-based Voice Conversion)',
    category: 'voice-conversion',
    runtime: 'rvc-bridge',
    presetId: 'rvc-local',
    version: '2',
    sizeGb: 0.6,
    license: 'MIT',
    requirements: { minVramGb: 0, recommendedVramGb: 4, minRamGb: 8, cpuOk: true, minCpuCores: 4 },
    capabilities: ['VOICE_CONVERSION'],
    homepage: 'https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI',
    notes: 'Only for voices you are authorized to use; consent is recorded with the voice (spec §36).',
  },
  {
    id: 'llama-3.1-8b-instruct',
    name: 'Llama 3.1 8B Instruct',
    category: 'composition',
    runtime: 'ollama',
    presetId: 'ollama',
    version: '3.1',
    sizeGb: 4.9,
    license: 'Llama 3.1 Community License',
    requirements: { minVramGb: 6, recommendedVramGb: 8, minRamGb: 8, cpuOk: true, minCpuCores: 8 },
    quantizations: [
      { id: 'Q4_K_M', sizeGb: 4.9, vramGb: 6, quality: 0.9 },
      { id: 'Q5_K_M', sizeGb: 5.7, vramGb: 7, quality: 0.93 },
      { id: 'Q8_0', sizeGb: 8.5, vramGb: 10, quality: 0.98 },
      { id: 'F16', sizeGb: 16.1, vramGb: 18, quality: 1 },
    ],
    capabilities: [...LLM_LOCAL, 'TOOL_CALLING', 'LONG_CONTEXT'],
    homepage: 'https://ollama.com/library/llama3.1',
    install: 'ollama pull llama3.1:8b',
    notes: 'Default Q4_K_M quantization; 128k context (raise num_ctx as memory allows).',
  },
  {
    id: 'qwen3-8b',
    name: 'Qwen3 8B',
    category: 'composition',
    runtime: 'ollama',
    presetId: 'ollama',
    version: '3',
    sizeGb: 5.2,
    license: 'Apache-2.0',
    requirements: { minVramGb: 6, recommendedVramGb: 8, minRamGb: 8, cpuOk: true, minCpuCores: 8 },
    quantizations: [
      { id: 'Q4_K_M', sizeGb: 5.2, vramGb: 6.5, quality: 0.9 },
      { id: 'Q8_0', sizeGb: 8.9, vramGb: 10.5, quality: 0.98 },
    ],
    capabilities: [...LLM_LOCAL, 'TOOL_CALLING'],
    homepage: 'https://ollama.com/library/qwen3',
    install: 'ollama pull qwen3:8b',
    notes: 'Strong reasoning for its size; may emit <think> blocks (stripped automatically).',
  },
  {
    id: 'gemma-3-12b',
    name: 'Gemma 3 12B',
    category: 'composition',
    runtime: 'ollama',
    presetId: 'ollama',
    version: '3',
    sizeGb: 8.1,
    license: 'Gemma Terms of Use',
    requirements: { minVramGb: 9, recommendedVramGb: 12, minRamGb: 16, cpuOk: true, minCpuCores: 8 },
    quantizations: [
      { id: 'Q4_K_M', sizeGb: 8.1, vramGb: 9.5, quality: 0.9 },
      { id: 'Q8_0', sizeGb: 13.4, vramGb: 15, quality: 0.98 },
    ],
    capabilities: [...LLM_LOCAL, 'LONG_CONTEXT'],
    homepage: 'https://ollama.com/library/gemma3',
    install: 'ollama pull gemma3:12b',
  },
  {
    id: 'mistral-small-3.2-24b',
    name: 'Mistral Small 3.2 (24B)',
    category: 'composition',
    runtime: 'ollama',
    presetId: 'ollama',
    version: '3.2',
    sizeGb: 15,
    license: 'Apache-2.0',
    requirements: { minVramGb: 16, recommendedVramGb: 24, minRamGb: 32, cpuOk: true, minCpuCores: 12 },
    quantizations: [
      { id: 'Q3_K_M', sizeGb: 11.5, vramGb: 13, quality: 0.85 },
      { id: 'Q4_K_M', sizeGb: 14.3, vramGb: 16, quality: 0.9 },
      { id: 'Q8_0', sizeGb: 25, vramGb: 27, quality: 0.98 },
    ],
    capabilities: [...LLM_LOCAL, 'TOOL_CALLING', 'LONG_CONTEXT'],
    homepage: 'https://ollama.com/library/mistral-small3.2',
    install: 'ollama pull mistral-small3.2',
  },
  {
    id: 'phi-4-mini',
    name: 'Phi-4-mini (3.8B)',
    category: 'composition',
    runtime: 'ollama',
    presetId: 'ollama',
    version: '4',
    sizeGb: 2.5,
    license: 'MIT',
    requirements: { minVramGb: 3, recommendedVramGb: 4, minRamGb: 8, cpuOk: true, minCpuCores: 4 },
    quantizations: [
      { id: 'Q4_K_M', sizeGb: 2.5, vramGb: 3.2, quality: 0.9 },
      { id: 'Q8_0', sizeGb: 4.1, vramGb: 5, quality: 0.98 },
    ],
    capabilities: [...LLM_LOCAL, 'LONG_CONTEXT'],
    homepage: 'https://ollama.com/library/phi4-mini',
    install: 'ollama pull phi4-mini',
    notes: 'Small and fast; good for drafts on laptops, weaker on complex edits.',
  },
  {
    id: 'matchering-2',
    name: 'Matchering 2 (reference mastering)',
    category: 'mastering',
    runtime: 'mastering-bridge',
    presetId: 'mastering-local',
    version: '2.0',
    sizeGb: 0.05,
    license: 'GPL-3.0',
    requirements: { minVramGb: 0, recommendedVramGb: 0, minRamGb: 4, cpuOk: true, minCpuCores: 2 },
    capabilities: ['MASTERING', 'REFERENCE_AUDIO'],
    homepage: 'https://github.com/sergree/matchering',
    install: 'pip install matchering',
    notes: 'Matches the loudness, frequency response and stereo width of a reference track.',
  },
];

export function catalogByCategory(category: LocalModelCategory): LocalModelEntry[] {
  return LOCAL_MODEL_CATALOG.filter((m) => m.category === category);
}

export function getCatalogModel(id: string): LocalModelEntry | undefined {
  return LOCAL_MODEL_CATALOG.find((m) => m.id === id);
}
